models/emergencycall.py
from extensions import db

class EmergencyCall(db.Model):
    __tablename__ = 'emergencycall'

    EmergencyCallID = db.Column(db.Integer, primary_key=True)
    SeniorUserID = db.Column(db.Integer, nullable=False)
    CallType = db.Column(db.String(4))

    __table_args__ = (
        db.ForeignKeyConstraint(['SeniorUserID'], ['senioruser.UserID']),
    )    

class EmergencyCallUser(db.Model):
    __tablename__ = 'emergencycalluser'
    EmergencyCallID= db.Column(db.Integer, primary_key=True)
    FamilyCaregiverID=db.Column(db.Integer, primary_key=True)
    HeartRate=db.Column(db.Integer, nullable=False)

    __table_args__ = (
        db.ForeignKeyConstraint(['EmergencyCallID'], ['emergencycall.EmergencyCallID']),
        db.ForeignKeyConstraint(['FamilyCaregiverID'], ['familycaregiver.UserID']),
    ) 

routes/report_routes.py
from flask import Flask, Blueprint, render_template, request, jsonify, url_for,redirect, flash
from models.user import User
from models.eldercareinstitutionevaluation import ElderCareInstitutionEvaluation
from models.funeralinstitutionevaluation import FuneralInstitutionEvaluation
from models.eldercareinstitution import ElderCareInstitution
from models.funeralinstitution import FuneralInstitution
from models.staffinstitution import StaffInstitution  # 导入StaffInstitution
from models.userrole import UserRole  # 导入UserRoles
from flask_bcrypt import Bcrypt
from flask_login import login_user, current_user, login_required
from extensions import db
from sqlalchemy.sql import func


# 判断机构类型并查询评价
def get_institution_type_by_id(institutionid):
    # 判断是否为养老机构
    elder_institution = ElderCareInstitutionEvaluation.query.filter_by(InstitutionID=institutionid).first()
    if elder_institution:
        return 'elder', elder_institution

    # 判断是否为殡葬机构
    funeral_institution = FuneralInstitutionEvaluation.query.filter_by(InstitutionID=institutionid).first()
    if funeral_institution:
        return 'funeral', funeral_institution

    return None, None  # 如果没有找到，返回 None


manage_report_bp = Blueprint('manage_report', __name__)
# 管理举报信息页面
@manage_report_bp.route('/manage_report', methods=['GET'])
@login_required
def manage_report():
    # 查询所有的养老机构和殡葬机构的举报，并获取机构名称
    elder_reports = ElderCareInstitutionEvaluation.query.filter(ElderCareInstitutionEvaluation.ReportInfo.isnot(None)).all()
    funeral_reports = FuneralInstitutionEvaluation.query.filter(FuneralInstitutionEvaluation.ReportInfo.isnot(None)).all()

    # 获取机构名称
    elder_institution_names = {}
    for report in elder_reports:
        institution = ElderCareInstitution.query.filter_by(InstitutionID=report.InstitutionID).first()
        elder_institution_names[report.InstitutionID] = institution.InstitutionName if institution else '未知'

    funeral_institution_names = {}
    for report in funeral_reports:
        institution = FuneralInstitution.query.filter_by(InstitutionID=report.InstitutionID).first()
        funeral_institution_names[report.InstitutionID] = institution.InstitutionName if institution else '未知'

    # 渲染举报信息页面
    return render_template('manage_report.html', elder_reports=elder_reports, funeral_reports=funeral_reports,
                           elder_institution_names=elder_institution_names, funeral_institution_names=funeral_institution_names)

@manage_report_bp.route('/edit_report/<int:InstitutionID>/<int:EvaluationID>', methods=['GET', 'POST'])
@login_required
def edit_report(InstitutionID,EvaluationID):
    institution_type, institution = get_institution_type_by_id(InstitutionID)
    
    if institution is None:
        return "Institution not found", 404

    # 获取机构名称
    if institution_type == 'elder':
        institution_name = ElderCareInstitution.query.filter_by(InstitutionID=InstitutionID).first().InstitutionName
        report_info = ElderCareInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first().ReportInfo

    elif institution_type == 'funeral':
        institution_name = FuneralInstitution.query.filter_by(InstitutionID=InstitutionID).first().InstitutionName
        report_info = FuneralInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first().ReportInfo

    # 如果是 GET 请求，显示现有的举报信息
    if request.method == 'GET':
        return render_template('edit_report.html', report_info=report_info, institution_type=institution_type,
                               institution_name=institution_name)

    # 如果是 POST 请求，更新举报信息
    new_report_info = request.form['report_info']
    
    # 根据机构类型更新举报信息
    if institution_type == 'elder':
        report = ElderCareInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first()
        if report:  # 如果报告存在，更新举报信息
            report.ReportInfo = new_report_info
    elif institution_type == 'funeral':
        report = FuneralInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first()
        if report:  # 如果报告存在，更新举报信息
            report.ReportInfo = new_report_info

    # 提交更新到数据库
    db.session.commit()

    return redirect(url_for('manage_report.manage_report'))

# 删除报告信息（仅清空 ReportInfo 字段）
@manage_report_bp.route('/delete_report/<int:InstitutionID>/<int:EvaluationID>', methods=['GET'])
@login_required
def delete_report(InstitutionID,EvaluationID):
    institution_type, institution = get_institution_type_by_id(InstitutionID)
    
    if institution is None:
        return "Institution not found", 404
    
    if institution_type == 'elder':
        report = ElderCareInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first()
        report.ReportInfo = None
    elif institution_type == 'funeral':
        report = FuneralInstitutionEvaluation.query.filter_by(EvaluationID=EvaluationID).first()
        report.ReportInfo = None
        
    db.session.commit()

    return redirect(url_for('manage_report.manage_report'))


routes/user_routes.py
from flask import Blueprint, render_template, request, jsonify,  url_for,flash, redirect
from models.user import User,SeniorUser, FamilyCareGiver, Staff, Supervisor, FamilySeniorRelation
from models.userrole import UserRole 
from models.eldercareinstitution import ElderCareInstitution 
from models.funeralinstitution import FuneralInstitution
from flask_bcrypt import Bcrypt
from flask_login import login_user, current_user, login_required
from extensions import db
from werkzeug.security import generate_password_hash


user_bp = Blueprint('user', __name__)

bcrypt = Bcrypt()

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(Username=username).first()

        if user:
            # 如果密码是明文的，重新哈希并更新数据库
            if not user.Password.startswith('$2b$'):
                hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                user.Password = hashed_password
                db.session.commit()

            # 检查哈希密码
            if bcrypt.check_password_hash(user.Password, password):
                login_user(user)
                return jsonify({"status": "success", "redirect_url": "/user/dashboard"})
        
        return jsonify({"status": "error", "message": "Invalid credentials"}), 401

    return render_template('login.html')


@user_bp.route('/dashboard')
@login_required
def dashboard():
    user = current_user
    user_role = UserRole.query.filter_by(UserID=user.UserID).first()  # 获取用户角色

    # 返回用户信息和角色
    return render_template('dashboard.html', user=user, role=user_role.Role)

@user_bp.route('/view_institutions', methods=['GET', 'POST'])
@login_required
def view_institutions():
    search_term = request.args.get('search', '')  # 获取搜索关键词
    street_town_filter = request.args.get('street_town', '')  # 获取StreetTown的筛选条件
    page = request.args.get('page', 1, type=int)
    institutions = []
    street_towns = []  # 用来存储所有唯一的 StreetTown 值

    table_type = request.args.get('type', '')  # 获取机构类型，'elderly' 或 'funeral'

    search_feedback = None
    if table_type == 'elderly':
        # 查找养老机构
        query = ElderCareInstitution.query.filter(ElderCareInstitution.InstitutionName.like(f'%{search_term}%'))
        
        # 如果有StreetTown的筛选条件，应用它
        if street_town_filter:
            query = query.filter(ElderCareInstitution.StreetTown == street_town_filter)
        
        institutions = query.paginate(page=page, per_page=10, error_out=False)
        # 获取所有唯一的 StreetTown 值，作为下拉框的选项
        street_towns = db.session.query(ElderCareInstitution.StreetTown).distinct().all()

    elif table_type == 'funeral':
        # 查找殡葬机构
        query = FuneralInstitution.query.filter(FuneralInstitution.InstitutionName.like(f'%{search_term}%'))
        
        # 如果搜索term为空，不做过滤
        if search_term:
            if not search_term:
                institutions = []
            else:
                query = query.filter(FuneralInstitution.Address.like(f'%{search_term}%'))

        if street_town_filter:
            query = query.filter(FuneralInstitution.Address == street_town_filter)
        
        institutions = query.paginate(page=page, per_page=10, error_out=False)
        # 获取所有唯一的 StreetTown 值，作为下拉框的选项
        street_towns = db.session.query(FuneralInstitution.Address).distinct().all()

    # 获取上一个页面的 URL
    referrer = request.referrer

    return render_template('view_institutions.html', 
                           institutions=institutions, 
                           table_type=table_type,
                           search_term=search_term,
                           street_towns=street_towns,
                           street_town_filter=street_town_filter,
                           search_feedback='No results found' if not institutions else None,
                           referrer=referrer)

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')  # 提供注册页面

    # 获取注册信息
    username = request.form.get('username')
    password = request.form.get('password')
    phone_number = request.form.get('phone_number')
    user_type = request.form.get('user_type')
    real_name = request.form.get('real_name')
    id_number = request.form.get('id_number')
    residence = request.form.get('residence')
    position = request.form.get('position')
    employee_number = request.form.get('employee_number')
    senior_user_id = request.form.get('senior_user_id')

    # 检查用户名是否已存在
    existing_user = User.query.filter_by(Username=username).first()
    if existing_user:
        flash('用户名已存在，请选择其他用户名。')
        return redirect(url_for('user.register'))  # 返回注册页面

    # 获取当前最大 UserID，并设置新用户的 UserID
    max_user_id = db.session.query(db.func.max(User.UserID)).scalar() or 0
    new_user_id = max_user_id + 1

    try:
        # 添加到 `users` 表
        new_user = User(
            UserID=new_user_id,
            Username=username,
            Password=generate_password_hash(password),
            PhoneNumber=phone_number
        )
        db.session.add(new_user)
        db.session.commit()

        # 添加到 `UserRole` 表
        role_id = int(user_type)  # 1-5
        role_name = {1: '一般用户', 2: '老年用户', 3: '家属、看护用户', 4: '机构管理用户', 5: '民政部门用户'}[role_id]
        new_user_role = UserRole(
            UserID=new_user_id,
            RoleID=role_id,
            Role=role_name
        )
        db.session.add(new_user_role)
        db.session.commit()

        # 根据用户类型添加到对应表
        if role_id == 2:  # 老年用户
            senior_user = SeniorUser(
                UserID=new_user_id,
                RealName=real_name,
                IDNumber=id_number,
                Residence=residence
            )
            db.session.add(senior_user)

        elif role_id == 3:  # 家属/看护用户
            senior_user = SeniorUser.query.filter_by(UserID=senior_user_id).first()
            if not senior_user:
                flash('绑定的老年用户不存在，请检查输入的老年用户ID')
                return redirect(url_for('user.register'))

            family_caregiver = FamilyCareGiver(
                UserID=new_user_id,
                RealName=real_name,
                IDNumber=id_number
            )
            db.session.add(family_caregiver)
            db.session.commit()

            # 更新 `familyseniorrelation` 表
            family_relation = FamilySeniorRelation(
                FamilyCaregiverID=new_user_id,
                SeniorUserID=senior_user_id
            )
            db.session.add(family_relation)

        elif role_id == 4:  # 机构管理用户
            staff = Staff(
                UserID=new_user_id,
                Position=position
            )
            db.session.add(staff)

        elif role_id == 5:  # 民政部门用户
            supervisor = Supervisor(
                UserID=new_user_id,
                Position=position,
                EmployeeNumber=employee_number
            )
            db.session.add(supervisor)

        # 提交所有更改
        db.session.commit()

        flash('注册成功！')
        return redirect(url_for('user.login'))  # 注册成功后跳转到登录页面

    except Exception as e:
        db.session.rollback()  # 回滚数据库操作
        flash(f'注册失败，请重试。错误: {str(e)}')
        return redirect(url_for('user.register'))  # 注册失败返回注册页面


templates/emergency_calls.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>呼救记录</title>


    
    <!-- 引入自定义 CSS 样式 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    <!-- 引入字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
</head>

<body>
    <div class="container py-4">
        <h1 class="text-center mb-4">您的呼救记录</h1>

        {% if emergency_calls %}
            <table class="table table-bordered table-striped">
                <thead class="table-light">
                    <tr>
                        <th>呼救编号</th>
                        <th>呼救类型</th>
                    </tr>
                </thead>
                <tbody>
                    {% for call in emergency_calls %}
                    <tr>
                        <td>{{ call.EmergencyCallID }}</td>
                        <td>{{ call.CallType }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="text-center">暂无呼救记录。</p>
        {% endif %}

        <h2 class="text-center mt-4">发起新的呼救</h2>
        <div class="text-center">
            <form method="POST" action="{{ url_for('emergencycall.manage_emergency_call') }}">
                <button type="submit" class="btn btn-danger btn-lg">自动呼救</button>
            </form>
        </div>

        <br>
        <div class="text-center">
            <a href="{{ url_for('user.dashboard') }}" class="btn btn-link">返回用户中心</a>
        </div>
    </div>
</body>
</html>

templates/heart_rate.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>心率信息</title>

    <!-- 引入 Bootstrap 样式表 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iN8QF6BdcYI6Wz6lm8fFXY5EXp9vnF9S0K9hb5g5uM2Gp6o3GqK8AB1Wy" crossorigin="anonymous">
    
    <!-- 自定义 CSS 样式 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    <!-- 引入字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
</head>

<body>
    <div class="container mt-5">
        {% if user_role == '老年用户' %}
            <h1>您的心率信息</h1>
        {% elif user_role == '家属、看护用户' %}
            <h1>您关联老年用户的心率信息</h1> 
        {% endif %}

        {% if heart_rate is not none %}
            <p><strong>心率：</strong>{{ heart_rate }} BPM</p>
            <p><strong>真实姓名：</strong>{{ real_name }}</p>
            <p><strong>所在地：</strong>{{ residence }}</p>
        {% else %}
            <p>暂无心率数据。</p>
        {% endif %}
        <br>

        <a href="{{ url_for('user.dashboard') }}" class="btn btn-secondary mt-3">返回用户中心</a>
    </div>
</body>
</html>

templates/manage_report.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>管理举报信息</title>

    <!-- 引入 Bootstrap 样式表 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iN8QF6BdcYI6Wz6lm8fFXY5EXp9vnF9S0K9hb5g5uM2Gp6o3GqK8AB1Wy" crossorigin="anonymous">
    
    <!-- 自定义 CSS 样式 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <!-- 引入字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
</head>

<body>
    <div class="container mt-5">
        <h1 class="mb-4">管理举报信息</h1>

        <h2>养老机构举报</h2>
        {% if elder_reports %}
            <ul>
            {% for report in elder_reports %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="card-title"><strong>机构名称:</strong> {{ elder_institution_names[report.InstitutionID] }}</p>
                    <p class="card-text"><strong>机构ID:</strong> {{ report.InstitutionID }}</p>
                    <p class="card-text"><strong>举报内容:</strong> {{ report.ReportInfo }}</p>
                    <div class="d-flex justify-content-between">
                        <a href="{{ url_for('manage_report.edit_report', InstitutionID=report.InstitutionID, EvaluationID=report.EvaluationID) }}">编辑举报</a>|
                        <a href="{{ url_for('manage_report.delete_report', InstitutionID=report.InstitutionID,EvaluationID=report.EvaluationID)}}">删除举报</a>
                    </div>
                </div>
            </div>            
            {% endfor %}
            </ul>
        {% else %}
            <p>没有举报信息</p>
        {% endif %}

        <h2>殡葬机构举报</h2>
        {% if funeral_reports %}
            <ul>
            {% for report in funeral_reports %}

                <p class="card-title"><strong>机构名称:</strong> {{ funeral_institution_names[report.InstitutionID] }}</p>
                <p class="card-text"><strong>机构ID:</strong> {{ report.InstitutionID }}</p>
                <p class="card-text"><strong>举报内容:</strong> {{ report.ReportInfo }}</p>
                        <a href="{{ url_for('manage_report.edit_report', InstitutionID=report.InstitutionID, EvaluationID=report.EvaluationID) }}">编辑举报</a>|
                        <a href="{{ url_for('manage_report.delete_report', InstitutionID=report.InstitutionID,EvaluationID=report.EvaluationID)}}">删除举报</a>
            {% endfor %}
            </ul>
        {% else %}
            <p>没有举报信息</p>
        {% endif %}
        <br>
        <a href="{{ url_for('user.dashboard') }}">返回用户中心</a>
    </div>
</body>
</html>

templates/view_emergency_calls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Emergency Calls</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- 引入 Bootstrap 样式表 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iN8QF6BdcYI6Wz6lm8fFXY5EXp9vnF9S0K9hb5g5uM2Gp6o3GqK8AB1Wy" crossorigin="anonymous">
    
    <!-- 自定义 CSS 样式 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    <!-- 引入字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
</head>

<body>
    <div class="container mt-4">
        <h1>您关联老年用户的呼救记录</h1>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>呼救编号</th>
                    <th>心率</th>
                    <th>老年用户编号</th>
                    <th>真实姓名</th>
                    <th>地址</th>
                </tr>
            </thead>
            <tbody>
                {% for call in emergency_calls %}
                <tr>
                    <td>{{ call.EmergencyCallID }}</td>
                    <td>{{ call.HeartRate }}</td>
                    <td>{{ call.SeniorUserID }}</td>
                    <td>{{ call.RealName }}</td>
                    <td>{{ call.Residence }}</td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="5" class="text-center">No more emergency calls found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('user.dashboard') }}">返回用户中心</a>
    </div>
</body>
</html>

templates/view_institutions.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Browse Institutions</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    <!-- 引入字体 -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    
<body>
    <div class="container mt-5">
        <h1>浏览机构</h1>
        <br>

        {% if not table_type %}
        <!-- 显示选择按钮 -->
        <form method="GET" action="{{ url_for('user.view_institutions') }}">
            <button type="submit" name="type" value="elderly" class="btn btn-primary">养老机构</button>
            <button type="submit" name="type" value="funeral" class="btn btn-secondary">殡葬机构</button>
            <br>
            <br>
            <a href="/user/dashboard">返回用户中心</a>
        </form>
        {% else %}
        <!-- 搜索框和表格 -->
        <form method="GET" action="{{ url_for('user.view_institutions') }}">
            <input type="hidden" name="type" value="{{ table_type }}">
            <div class="form-group">
                <input type="text" name="search" class="form-control" placeholder="搜索机构" value="{{ search_term }}">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
            <button type="button" onclick="window.location.href='/user/view_institutions'" class="btn btn-secondary">返回</button>
        </form>

        {% if search_feedback %}
        <div class="alert alert-warning mt-3">
            {{ search_feedback }}
        </div>
        {% endif %}

            
            {% if table_type == 'elderly' %}
                <h2>养老机构</h2>
                <!-- StreetTown 筛选框 -->
                <form method="GET" action="{{ url_for('user.view_institutions') }}">
                    <input type="hidden" name="type" value="elderly">
                    <div class="form-group">
                        <label for="street_town_filter">街道/乡镇</label>
                        <select name="street_town" class="form-control" id="street_town_filter">
                            <option value="">选择一个街道/乡镇</option>
                            {% for street_town in street_towns %}
                                <option value="{{ street_town[0] }}" {% if street_town[0] == street_town_filter %}selected{% endif %}>{{ street_town[0] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">筛选</button>
                </form>

                <table class="table table-striped mt-3">
                    <thead>
                        <tr>
                            <th>机构名称</th>
                            <th>街道/乡镇</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for institution in institutions %}
                        <tr>
                            <td>{{ institution.InstitutionName }}</td>
                            <td class="ellipsis">{{ institution.StreetTown }}</td>
                            <td>
                                <button class="btn btn-info btn-sm toggle-details" data-target="#details-{{ institution.InstitutionID }}">查看详情信息</button>
                                <a href="{{ url_for('review.view_evaluations', InstitutionID=institution.InstitutionID) }}" class="btn btn-warning btn-sm">查看评价</a>
                                <a href="{{ url_for('review.view_reports', InstitutionID=institution.InstitutionID) }}" class="btn btn-warning btn-sm">查看举报</a>
                            </td>
                        </tr>
                        <tr id="details-{{ institution.InstitutionID }}" class="collapse">
                            <td colspan="3">
                                <strong>机构名称：</strong> {{ institution.InstitutionName }}<br>
                                <strong>街道/乡镇：</strong> {{ institution.StreetTown }}<br>
                                <strong>床位数：</strong> {{ institution.BedCount }}<br>
                                <strong>详细地址：</strong> {{ institution.Address }}<br>
                                <strong>联系电话：</strong> {{ institution.PhoneNumber }}<br>
                                <strong>邮编：</strong> {{ institution.PostalCode }}<br>
                                <strong>运营模式：</strong> {{ institution.OperationMode }}<br>
                                <strong>法人代表：</strong> {{ institution.LegalRepresentative }}<br>
                                <strong>创办时间：</strong> {{ institution.OperationYearMonth }}<br>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    </tbody>
                </table>
            {% elif table_type == 'funeral' %}
                <h2>殡葬机构</h2>
                <table class="table table-striped mt-3">
                    <thead>
                        <tr>
                            <th>机构名称</th>
                            <th>地址</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for institution in institutions %}
                        <tr>
                            <td>{{ institution.InstitutionName }}</td>
                            <td class="ellipsis">{{ institution.Address }}</td>
                            <td>
                                <button class="btn btn-info btn-sm toggle-details" data-target="#details-{{ institution.InstitutionID }}">查看详情信息</button>
                                <a href="{{ url_for('review.view_evaluations', InstitutionID=institution.InstitutionID) }}" class="btn btn-warning btn-sm">查看评价</a>
                                <a href="{{ url_for('review.view_reports', InstitutionID=institution.InstitutionID) }}" class="btn btn-warning btn-sm">查看举报</a>
                            </td>
                        </tr>
                        <tr id="details-{{ institution.InstitutionID }}" class="collapse">
                            <td colspan="3">
                                <strong>机构名称：</strong> {{ institution.InstitutionName }}<br>
                                <strong>详细地址：</strong> {{ institution.Address }}<br>
                                <strong>联系电话：</strong> {{ institution.PhoneNumber }}<br>
                                <strong>邮编：</strong> {{ institution.PostalCode }}<br>
                                <strong>联系人：</strong> {{ institution.ContactPerson }}<br>
                                <strong>机构种类：</strong> {{ institution.InstitutionType }}<br>
                                <strong>服务范围：</strong> {{ institution.ServiceScope }}<br>
                            </td>
                        </tr>
                       
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <div class="pagination">
                {% if institutions.has_prev %}
                    <a href="{{ url_for('user.view_institutions', page=institutions.prev_num, type=table_type, search=search_term, street_town=street_town_filter) }}" class="btn btn-primary">上一页</a>
                {% endif %}
            
                <span>第 {{ institutions.page }} 页</span>
            
                {% if institutions.has_next %}
                    <a href="{{ url_for('user.view_institutions', page=institutions.next_num, type=table_type, search=search_term, street_town=street_town_filter) }}" class="btn btn-primary">下一页</a>
                {% endif %}

                <span style="float: right;">共 {{ institutions.pages }} 页</span>
            </div>            
        {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            // 避免重复的折叠动作
            $('.toggle-details').click(function() {
                var target = $(this).data('target');
                $(target).toggleClass('collapse');
            });

            $('.toggle-evaluation').click(function() {
                var target = $(this).data('target');
                $(target).toggleClass('collapse');
            });
        });
    </script>
</body>
</html>